---
- hosts: mailservers
  tasks:
    # dovecot
    - name: install dovecot
      yum: name=dovecot state=present
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: dovecot main config
      copy: dest=/etc/dovecot/dovecot.conf src=files/dovecot.conf
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: dovecot authentication config
      copy: dest=/etc/dovecot/conf.d/10-auth.conf src=files/dovecot-10-auth.conf
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: dovecot mail location config
      copy: dest=/etc/dovecot/conf.d/10-mail.conf src=files/dovecot-10-mail.conf
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: dovecot logging config
      copy: dest=/etc/dovecot/conf.d/10-logging.conf src=files/dovecot-10-logging.conf
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: dovecot ssl config
      copy: dest=/etc/dovecot/conf.d/10-ssl.conf src=files/dovecot-10-ssl.conf
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: dovecot smtp auth
      copy: dest=/etc/dovecot/conf.d/10-master.conf src=files/dovecot-10-master.conf
      notify:
        - restart dovecot
      tags:
        - dovecot

    - name: verify that dovecot is enabled
      service: name=dovecot enabled=true
      notify:
        - restart dovecot
      tags:
        - dovecot

    # postfix
    - name: install postfix
      yum: name=postfix state=present
      notify:
        - restart postfix
      tags:
        - postfix

    - name: verify that sendmail is removed
      yum: name=sendmail state=absent
      tags:
        - postfix

    - name: postfix main config
      template: dest=/etc/postfix/main.cf src=templates/postfix-main.cf.j2
      notify:
        - restart postfix
      tags:
        - postfix

    - name: postfix master config
      copy: dest=/etc/postfix/master.cf src=files/postfix-master.cf
      notify:
        - restart postfix
      tags:
        - postfix

    - name: copy postfix virtual
      template: dest=/etc/postfix/virtual src=templates/postfix-virtual.j2
      notify:
        - run virtual postmap
        - restart postfix
        - generate aliases
      tags:
        - postfix
      when: is_primary_mailserver

    - name: copy postfix generics
      template: dest=/etc/postfix/generic src=templates/postfix-generic.j2
      notify:
        - run generic postmap
      tags:
        - postfix
      when: is_primary_mailserver

    - name: copy postfix transport config
      template: dest=/etc/postfix/transport src=templates/postfix-transport.j2
      notify:
        - run transport postmap
      tags:
        - postfix
      when: not is_primary_mailserver

    - name: set up aliases
      template: dest=/etc/aliases src=templates/mail-aliases.j2
      notify:
        - generate aliases
      tags:
        - postfix
      when: is_primary_mailserver

    - name: verify that postfix is enabled
      service: name=postfix enabled=true
      tags:
        - postfix

    # procmail
    - name: verify that procmail is installed
      yum: name=procmail state=present
      tags:
        - procmail

    # spamassassin
    - name: install spamassassin
      yum: name=spamassassin state=present
      notify:
        - restart spamassassin
      tags:
        - spamassassin

    - name: copy spamassassin local.cf
      copy: dest=/etc/mail/spamassassin/local.cf src=files/spamassassin-local.cf
      notify:
        - restart postfix
        - restart spamassassin
      tags:
        - spamassassin

    - name: create cronjob for spamassassin
      cron: name=sa-update hour="10" job="/usr/bin/sa-update"
      tags:
        - spamassassin

    - name: create spamd group
      group: name=spamd state=present
      tags:
        - spamassassin

    - name: create spamd user
      user: name=spamd state=present shell=/bin/false group=spamd
      tags:
        - spamassassin

    - name: verify that spamassassin is enabled
      service: name=spamassassin enabled=true
      tags:
        - spamassassin

    - name: verify iptables rules are in place
      file: path=/etc/sysconfig/iptables src=files/iptables
      notify:
        - restart iptables
      tags:
        - firewall

    - name: verify SSL cert is in place
      file: path=/etc/ssl/certs/server.crt src=files/mailserver.crt
      notify:
        - restart dovecot
        - restart postfix
      tags:
        - certs

    - name: verify SSL key is in place
      file: path=/etc/ssl/certs/server.key src=files/mailserver.key
      notify:
        - restart dovecot
        - restart postfix
      tags:
        - certs

  handlers:
    - name: generate aliases
      command: /usr/bin/newaliases

    - name: restart dovecot
      service: name=dovecot state=restarted

    - name: restart iptables
      service: name=iptables state=restarted

    - name: restart opendkim
      service: name=opendkim state=restarted

    - name: restart postfix
      service: name=postfix state=restarted

    - name: restart spamassassin
      service: name=spamassassin state=restarted

    - name: run virtual postmap
      command: /usr/sbin/postmap /etc/postfix/virtual

    - name: run generic postmap
      command: /usr/sbin/postmap /etc/postfix/generic

    - name: run transport postmap
      command: /usr/sbin/postmap /etc/postfix/transport
