---
- hosts: all
  tasks:
    # dovecot
    - name: install dovecot
      yum: name=dovecot state=present
      notify:
        - restart dovecot

    - name: dovecot main config
      copy: dest=/etc/dovecot/dovecot.conf src=files/dovecot.conf
      notify:
        - restart dovecot

    - name: dovecot authentication config
      copy: dest=/etc/dovecot/conf.d/10-auth.conf src=files/dovecot-10-auth.conf
      notify:
        - restart dovecot

    - name: dovecot mail location config
      copy: dest=/etc/dovecot/conf.d/10-mail.conf src=files/dovecot-10-mail.conf
      notify:
        - restart dovecot

    - name: dovecot smtp auth
      copy: dest=/etc/dovecot/conf.d/10-master.conf src=files/dovecot-10-master.conf
      notify:
        - restart dovecot

    - name: verify that dovecot is enabled
      service: name=dovecot enabled=true
      notify:
        - restart dovecot

    # postfix
    - name: install postfix
      yum: name=postfix state=present
      notify:
        - restart postfix

    - name: verify that sendmail is removed
      yum: name=sendmail state=absent

    - name: postfix main config
      template: dest=/etc/postfix/main.cf src=files/postfix-main.cf.j2
      notify:
        - restart postfix

    - name: postfix master config
      copy: dest=/etc/postfix/master.cf src=files/postfix-master.cf
      notify:
        - restart postfix

    - name: set up aliases
      copy: dest=/etc/aliases src=files/mail-aliases
      notify:
        - generate aliases

    - name: verify that postfix is enabled
      service: name=postfix enabled=true

    # spamassassin
    - name: install spamassassin
      yum: name=spamassassin state=present
      notify:
        - restart spamassassin

    - name: copy spamassassin local.cf
      copy: dest=/etc/mail/spamassassin/local.cf src=files/spamassassin-local.cf
      notify:
        - restart postfix
        - restart spamassassin

    - name: create cronjob for spamassassin
      cron: hour="10" job="sa-update && service spamassassin reload"

    - name: create spamd group
      group: name=spamd state=present

    - name: create spamd user
      user: name=spamd state=present shell=/bin/false group=spamd

    - name: verify that spamassassin is enabled
      service: name=spamassassin enabled=true

  handlers:
    - name: generate aliases
      command: /usr/bin/newaliases

    - name: restart dovecot
      service: name=dovecot state=restarted

    - name: restart postfix
      service: name=postfix state=restarted

    - name: restart spamassassin
      service: name=spamassassin state=restarted
